// Hand-traced test: every expected value below was worked out by hand
// from the event sequence, not generated by running the code and
// copying its output. That distinction matters -- a test that just
// echoes back whatever the implementation produces can't catch a bug
// in that implementation.
//
// Scenario (all prices in LOBSTER units, $ * 10000):
//   t=1  id=1  BUY  100 @ 999900   (new)      book: bid 999900 x100
//   t=2  id=2  BUY  200 @ 999800   (new)      book: bids {999900:100, 999800:200}
//   t=3  id=3  SELL 150 @ 1000100  (new)      book: ask 1000100 x150
//   t=4  id=1  partial cancel 40             -> id=1 now 60, KEEPS front position
//   t=5  id=4  BUY  50  @ 999900   (new)      joins id=1's level, behind it
//   t=6  id=1  executed 60                    -> id=1 fully filled, removed
//   t=7  id=2  total delete                   -> id=2 removed entirely
//
// Expected final state:
//   bids: level 999900 has only id=4 (size 50); level 999800 is gone
//   asks: level 1000100 has id=3 (size 150), untouched throughout
//   best bid = 999900, best ask = 1000100

#include "order_book.hpp"
#include <cassert>
#include <iostream>

using namespace lob;

static int failures = 0;

#define CHECK(cond, msg) \
    do { \
        if (!(cond)) { \
            std::cerr << "FAIL: " << msg << " (line " << __LINE__ << ")\n"; \
            ++failures; \
        } else { \
            std::cout << "PASS: " << msg << "\n"; \
        } \
    } while (0)

int main() {
    OrderBook book;

    book.addLimitOrder(1, Side::Buy, 999900, 100, 1.0);
    book.addLimitOrder(2, Side::Buy, 999800, 200, 2.0);
    book.addLimitOrder(3, Side::Sell, 1000100, 150, 3.0);

    CHECK(book.bestBid().value() == 999900, "best bid is 999900 after two buy orders");
    CHECK(book.bestAsk().value() == 1000100, "best ask is 1000100 after one sell order");

    book.cancelPartial(1, 40); // id=1: 100 -> 60, keeps queue position
    CHECK(book.sizeAheadOf(1) == 0, "id=1 still at front of its level after partial cancel");

    book.addLimitOrder(4, Side::Buy, 999900, 50, 5.0); // joins behind id=1
    CHECK(book.sizeAheadOf(4) == 60, "id=4 has id=1's remaining 60 shares ahead of it");

    book.executeOrder(1, 60); // fully fills id=1 -> removed
    CHECK(book.sizeAheadOf(4) == 0, "id=4 moves to front once id=1 is fully executed");

    book.deleteOrder(2); // remove the 999800 level entirely

    auto bids = book.bidLevels(5);
    CHECK(bids.size() == 1, "only one bid level remains (999800 deleted)");
    CHECK(bids[0].price == 999900, "remaining bid level is 999900");
    CHECK(bids[0].size == 50, "remaining bid level size is 50 (id=4 only, id=1 fully filled)");

    auto asks = book.askLevels(5);
    CHECK(asks.size() == 1, "ask side untouched: still one level");
    CHECK(asks[0].price == 1000100 && asks[0].size == 150, "ask level unchanged at 150");

    CHECK(book.bestBid().value() == 999900, "final best bid");
    CHECK(book.bestAsk().value() == 1000100, "final best ask");
    CHECK(book.orderCount() == 2, "exactly 2 live orders remain (id=3, id=4)");

    if (failures == 0) {
        std::cout << "\nAll hand-traced checks passed.\n";
        return 0;
    } else {
        std::cout << "\n" << failures << " check(s) FAILED.\n";
        return 1;
    }
}
