"""
Robustness check for the naive-vs-Avellaneda-Stoikov finding: does it
hold up across MANY independent synthetic sessions, or was the original
one-file result (data/synthetic_large.csv, one seed) an artifact of
that particular random draw?

Runs three strategies across N_SEEDS independent sessions, each
generated by generate_realistic_lobster_data() (fat-tailed,
volatility-clustered order flow -- see generate_synthetic_data.py and
tests/test_synthetic_data_realism.py for why this generator rather than
the plain random-walk one is used for this robustness check):

    naive        -- naive symmetric market maker (the baseline)
    as_fixed     -- Avellaneda-Stoikov, gamma=0.01, FIXED session-end
                    horizon (the original, pathological configuration
                    from the README's main finding: near-zero fills)
    as_rolling   -- Avellaneda-Stoikov, gamma=0.01, 10s ROLLING horizon
                    (the fix from the rolling-horizon finding)

Each session recalibrates sigma/kappa from ITS OWN data, exactly as
run_comparison.py does for the single-file case -- no strategy is ever
tested against parameters fit on a different session's data, which
would make the comparison meaningless.
"""
import sys
import os
import statistics
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import lob_engine as lob
from strategies.naive_mm import NaiveMarketMaker, NaiveMarketMakerConfig
from strategies.avellaneda_stoikov import AvellanedaStoikov, AvellanedaStoikovConfig
from backtest.replay_backtest import ReplayBacktest
from backtest.calibrate import estimate_sigma_from_events, estimate_kappa_from_events
from backtest.generate_synthetic_data import generate_realistic_lobster_data


def run_one_seed(seed, tmp_path, n_events=2000, gamma=0.01, tick_size=100,
                  quote_size=100, max_inventory=500, rolling_horizon=10.0):
    generate_realistic_lobster_data(n_events=n_events, seed=seed, output_path=tmp_path)
    events = lob.read_message_file(tmp_path)
    if len(events) < 20:
        return None  # too little data in this session to calibrate meaningfully -- skip it

    sigma = estimate_sigma_from_events(events)
    try:
        kappa = estimate_kappa_from_events(events, tick_size=tick_size)
    except ValueError:
        # calibrate.py's own documented failure mode: this session's order
        # flow didn't show fill-intensity decreasing with distance from the
        # best price clearly enough to fit a kappa from. A real, expected
        # outcome on SOME random sessions, not a bug -- skip this seed
        # rather than force a nonsensical kappa on it.
        return None
    last_time = events[-1].time

    def make_as(horizon):
        cfg = AvellanedaStoikovConfig(gamma=gamma, kappa=kappa, sigma=sigma, session_end_time=last_time,
                                       horizon=horizon, tick_size=tick_size, quote_size=quote_size,
                                       max_inventory=max_inventory)
        return AvellanedaStoikov(cfg)

    naive_cfg = NaiveMarketMakerConfig(half_spread_ticks=1, tick_size=tick_size, quote_size=quote_size,
                                        max_inventory=max_inventory)
    strategies = {
        "naive": NaiveMarketMaker(naive_cfg),
        "as_fixed": make_as(horizon=None),
        "as_rolling": make_as(horizon=rolling_horizon),
    }

    results = {}
    for name, strat in strategies.items():
        history = ReplayBacktest(events, strat).run()
        final_mtm = history[-1][1] if history else 0.0
        results[name] = {"fills": len(strat.fills), "final_mtm": final_mtm}
    return results


def main(n_seeds=50, n_events=2000):
    all_results = {"naive": [], "as_fixed": [], "as_rolling": []}

    with tempfile.NamedTemporaryFile(suffix=".csv") as f:
        for seed in range(n_seeds):
            r = run_one_seed(seed, tmp_path=f.name, n_events=n_events)
            if r is None:
                continue
            for name in all_results:
                all_results[name].append(r[name])

    n = len(all_results["naive"])
    print(f"Ran {n} independent synthetic sessions (of {n_seeds} attempted, {n_events} events each)\n")

    print(f"{'strategy':<12} {'mean fills':>11} {'sessions w/ fills':>18} {'mean final MTM':>16} {'median final MTM':>18}")
    print("-" * 80)
    for name in all_results:
        fills = [r["fills"] for r in all_results[name]]
        mtms = [r["final_mtm"] for r in all_results[name]]
        pct_traded = 100.0 * sum(1 for f in fills if f > 0) / n
        print(f"{name:<12} {statistics.mean(fills):>11.2f} {pct_traded:>17.1f}% "
              f"{statistics.mean(mtms):>16.2f} {statistics.median(mtms):>18.2f}")

    naive_mtms = [r["final_mtm"] for r in all_results["naive"]]
    print()
    for name in ("as_fixed", "as_rolling"):
        other_mtms = [r["final_mtm"] for r in all_results[name]]
        naive_strictly_better = sum(1 for a, b in zip(naive_mtms, other_mtms) if a > b)
        tied = sum(1 for a, b in zip(naive_mtms, other_mtms) if a == b)
        print(f"naive beats {name} on final MTM in {naive_strictly_better}/{n} sessions "
              f"({100 * naive_strictly_better / n:.1f}%), tied in {tied}/{n}")

    return all_results


if __name__ == "__main__":
    main()
